### ISSUE TITLE
关于Json-Assistant一些优化建议

### ISSUE THREAD

**Issue by fanderboy** [MemoryZy/Json-Assistant#28]
### 需求/建议描述

1.Convert to Json功能现在只能生成默认值
2.idea中插件侧边栏叫Json Viewer和插件本身的名称不一致，以为是应用市场中的Json Viewer插件，以及图标也和应用市场中的不一致
![image](https://github.com/user-attachments/assets/757d0886-8cca-4662-803f-8f31a6081e00)

### 建议的解决方案

1.Convert to Json功能增加生成字段对应随机值的功能；
2.idea中插件侧边栏建议修改为和插件名称一致--Json Assistant，图标建议和应用市场中插件图标保持一致，更有区分度

**Comment by MemoryZy** [comment]
[新版本](https://plugins.jetbrains.com/plugin/24738-json-assistant/versions)已经上传，侧边窗口的名称、图标已更改。关于类属性转JSON是否包含随机值，我使用配置，由使用者决定是否开启，在IDEA的Setting -> Tools -> Json Assistant中。

**Comment by fanderboy** [comment]
好的，感谢
